apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-zero-cluster
  labels:
    app: kubernetes-zero-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-zero-cluster
  template:
    metadata:
      labels:
        app: kubernetes-zero-cluster
    spec:
      containers:
      - name: kubernetes-zero-cluster
        image: kubernetes-zero-cluster:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3