apiVersion: v1
kind: Service
metadata:
  name: kubernetes-zero-cluster-service
  labels:
    app: kubernetes-zero-cluster
spec:
  type: NodePort
  selector:
    app: kubernetes-zero-cluster
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30100
    protocol: TCP
    name: http
